### ISSUE TITLE
审核被拒

### ISSUE THREAD

**Issue by K999999999** [amisare/NNNavigationBar#1]
Non-public API usage:

The app references non-public selectors in xxx: _activeBarMetrics, _barPosition, _cancelInteractiveTransition:completionSpeed:completionCurve:, _completePopOperationAnimated:transitionAssistant:, _completePushOperationAnimated:transitionAssistant:, _didVisibleItemsChangeWithNewItems:oldItems:, _finishInteractiveTransition:completionSpeed:completionCurve:, _popNavigationItemWithTransition:, _pushNavigationItem:transition:, _updateInteractiveTransition:
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.
上面是苹果机审打回来的原因，现在审核很严，这种hook的方法看来已经不行了，望知悉。

**Comment by amisare** [comment]
非常感谢反馈。今天已经开始思考实现方式，已经有了大概的解决思路，需要后续验证。希望继续关注。
这里想和你确认下情况：此次提交的app是第一次提交appStore审核吗？

**Comment by amisare** [comment]
已解决：[https://github.com/amisare/NNNavigationBar/tree/fix-tryFix-issue-%231](https://github.com/amisare/NNNavigationBar/tree/fix-tryFix-issue-%231)
