### ISSUE TITLE
侧滑时过渡优化

### ISSUE THREAD

**Issue by fuchenxi** [amisare/NNNavigationBar#10]
A.nn_backgroundAlpha = 1.f; 
B.nn_backgroundAlpha = 0.f;
A.statusBar.hidden = NO
B.statusBar.hidden = YES
此时侧滑返回 导航栏的白色背景少了状态栏那一块

**Comment by amisare** [comment]
按照给的伪代码提示，测试了下没有复现。能否提供复现的 Demo ？比如 Demo 的 github 地址？
