### ISSUE TITLE
文档中所提，rightBarButtonItem 变浅的问题

### ISSUE THREAD

**Issue by fuchenxi** [amisare/NNNavigationBar#12]
[self.navigationItem.rightBarButtonItem setTitleTextAttributes:@{NSForegroundColorAttributeName : UIColor.h1TitleColor, NSFontAttributeName : FONT(12)} forState:UIControlStateNormal];
    [self.navigationItem.rightBarButtonItem setTitleTextAttributes:@{NSForegroundColorAttributeName : UIColor.h1TitleColor, NSFontAttributeName : FONT(12)} forState:UIControlStateHighlighted];
    [self.navigationItem.rightBarButtonItem setTitleTextAttributes:@{NSForegroundColorAttributeName : UIColor.h1TitleColor, NSFontAttributeName : FONT(12)} forState:UIControlStateDisabled];

**Comment by amisare** [comment]
非常感谢，已将 issue 的方法添加到 bug 描述的解决方法中
