### ISSUE TITLE
如何加个导航栏的分割线来实现润滑的过渡效果？ 

### ISSUE THREAD

**Issue by fuchenxi** [amisare/NNNavigationBar#13]
A页面有分割线 
B页面无分割线
C 类似于个人中心， 默认透明导航栏无分割线， 滑动一定偏移量之后显示导航栏和分割线
这种实现方式应该可以和您导航栏实现方式使用同样的方法实现吧？

**Comment by amisare** [comment]
根据你的描述，理论上是可以使用同样的方法实现的。NNNavigationBar 暂时没有提供 view 容器！
