### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [amisare/NNNavigationBar#3]
Hello Sir. I'm a UI/UX and Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before.

**Comment by amisare** [comment]
This is a great idea. You just need to fork the project and put the logo in a new folder which named ‘Logo’ or any name you think is great in the root of the project. The project is used to implement the translucent transition of the navigation bar during the ios interface switching process, I hope this can help you and look forward your work.

**Comment by anharismail** [comment]
Hello @amisare. These are my logo proposal for your project.
I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.
I'll provide all file types and sizes you needed.

Which one do you like?

### Version 1
![nnnavigationbar ver 1](https://user-images.githubusercontent.com/37614260/44143006-3c462526-a0ac-11e8-9c5e-c21506cf0953.png)

### Version 2
![nnnavigationbar ver 2](https://user-images.githubusercontent.com/37614260/44143025-4f5cb44a-a0ac-11e8-9a87-8abe7c138c68.png)

**Comment by amisare** [comment]
Both are grate, at my frist sight,  I prefer the version 2.
I have a plan and I want use it in the Demo. And some size images may be needed here.
I summarize the dimensions of all the images and reply to you here after I finish.

**Comment by anharismail** [comment]
Thanks for your response, I'll wait for it.

**Comment by amisare** [comment]
Here are all sizes of Image.The unit is px.
Icon （40 x 40, 60 x 60, 58 x 58, 87 x 87, 80 x 80, 120 x 120, 180 x 180 ).
LaunchImage (640 x 960, 640 x 1136, 750 x 1134, 1242 x 2208,  1125 x 2436).
Thank you.

**Comment by anharismail** [comment]
Hi @amisare, here I provide any files you needed

All Files: https://drive.google.com/drive/u/1/folders/10N5-sr1iRbnwWWHXqFTMCW0MDV3weLF4

**Comment by amisare** [comment]
Greate work，I will use them immediately.

**Comment by amisare** [comment]
I have used them in the project. Thanks for your contribution.
