### ISSUE TITLE
标题的字体颜色无法修改

### ISSUE THREAD

**Issue by iOSchuang** [amisare/NNNavigationBar#5]
标题字体颜色无法修改，不是指状态栏的标题。控制器的title的字体颜色

**Comment by amisare** [comment]
😯，开始理解错了，已经开始增加这个功能了

**Comment by iOSchuang** [comment]
OK,改好通知一声，我替换成这个框架，否则到焊条有背景色，黑色字体太丑了。
后期可以给导航条背景添加渐变色哈，辛苦啦

**Comment by amisare** [comment]
### 尝试实现失败
系统 UINavigationBar 对标题的渲染过程比较特殊，过度的过程中标题和 UIBarButtonItem 颜色不统一（无法实现一致的颜色过度，UIBarButtonItem 会提前渲染成下级页面 title 的颜色，而 title 的颜色会在下级页面显示后渲染—— UINavigationBar 的返回按钮样式是由上级页面设置的）。

### 建议通过原生方式实现
#### 1.通过 UINavigationBar.titleTextAttributes 设置 title 属性

如果项目中 title 属性仅有可数的几个位置有变化，可以通过 UINavigationBar.titleTextAttributes 设置 title 样式属性，类似 NSAttributedString 富文本。

也可以通过 `UIAppearance ` 进行全局设置：
```
UINavigationBar *appearance = [UINavigationBar appearance];
……
设置样式代码
……
```

#### 2.通过 UIViewController.navigationItem 自定义 titleView

每个 UIViewController 都自带一个 UINavigationItem 类型的 navigationItem 属性，UINavigationItem 类中有一个 titleView 属性，可以通过该属性指定每个 vc 中 title 的样式。例如：在项目 UIViewController 基类中为 navigationItem.titleView 属性自定义 view ，就在每个 vc 中修改 view 获得期望的 title 样式。

UINavigationItem.titleView 文档注释：
```
// Custom view to use in lieu of a title. May be sized horizontally. Only used when item is topmost on the stack.
```

**Comment by iOSchuang** [comment]
方法一尝试过，没成功。方法二应该没问题，我试一下！谢谢
